.PHONY: clean All

All:
	@echo "----------Building project:[ NumberGuessingGame - Debug ]----------"
	@cd "NumberGuessingGame" && "$(MAKE)" -f  "NumberGuessingGame.mk"
clean:
	@echo "----------Cleaning project:[ NumberGuessingGame - Debug ]----------"
	@cd "NumberGuessingGame" && "$(MAKE)" -f  "NumberGuessingGame.mk" clean
